### ISSUE TITLE
Basic Docs

### ISSUE THREAD

**Issue by justheuristic** [learning-at-home/tesseract#5]
* [x] update README.md
* [x] move documentation readthedocs.org
* [x] issue templates
* [ ] add tutorial

**Comment by UARTman** [comment]
Will update README tomorrow, removing experiment info and commenting on limitations (primarily DHT ones). Feel free to add our change when I'm done.

**Comment by UARTman** [comment]
Created a branch with updated README.

**Comment by justheuristic** [comment]
Master branch currently has all the technical stuff that's required for documentation. We can now accumulate the actual content for documentation, tutorials, templates, etc. 

I'm closing this issue and distributing what's left to more specific ones (e.g. about quickstart tutorial, about templates, etc.)
